### ISSUE TITLE
Criação do Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by Holyspear** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#1]
Necessário a criação de um ambiente de desenvolvimento, contendo as seguintes ferramentas:
1 - Instalação do JDK 8 para desenvolvimento em JAVA;
2 - Instalação e configuração da ferramenta IDE ECLIPSE LUNA ou MARS, integrando com repositório do GitHub;
3 - Instalação e configuração da base de dados POSTGREES;
4 - Instalação e configuração das API's principais (SONAR, MAVEN, HIBERNATE, JUNIT e JENKINS);
5 - Finalização do Container do Projeto para distribuição.

**Comment by rhawan** [comment]
Criação do projeto inicial finalizada. Será utilizado o framework Spring Boot
