### ISSUE TITLE
Documentação de Requisitos do Cadastro de Clientes

### ISSUE THREAD

**Issue by Holyspear** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#2]
Levantar principais requisitos da aplicação e criar documentação de requisitos para consolidar o protótipo da view que compõe o cadastro de clientes. Esta atividade exige:
1 - Questionário de requisitos da janela de cadastro;
2 - Campos que compõe a janela de cadastro;
3 - Obrigatoriedade e validações;
4 - Diagrama de Caso de Uso da aplicação;
5 - Protótipo da janela de cadastro.

**Comment by IraniAlves** [comment]
[CadastroCliente-Irani.pdf](https://github.com/FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano/files/650760/CadastroCliente-Irani.pdf)

**Comment by rhawan** [comment]
Irani, favor commitar este arquivo no projeto e fechar esta issue, já foi concluída.

**Comment by IraniAlves** [comment]
Foi adicionado o documento de Requisitos da tela de cadastro de clientes no wiki do projeto, conforme link abaixo:
:https://github.com/FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano/wiki/Documenta%C3%A7%C3%A3o-do-Projeto
