### ISSUE TITLE
Configuração do ambiente de Banco de Dados e criação do diagrama DER da aplicação

### ISSUE THREAD

**Issue by Holyspear** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#3]
Esta atividade é para criação do ambiente de banco de dados da aplicação, bem como sua configuração, criação de esquema e diagrama de entidade-relacionamento da aplicação proposta.
Para esta atividade, exige-se os seguintes passos:
1 - Criação do banco de dados na aplicação já configurada e instalada POSTGREES;
2 - Definição do nome do banco de dados;
3 - Criação de usuários do banco de dados;
4 - Configuração do banco com o pool de conexões da aplicação configurada no HIBERNATE;
5 - Criação do DER (Diagrama Entidade-Relacionamento) para o ambiente de cadastro de clientes;

Esta atividade está ligada à atividade de criação do documento de requisitos, necessitando de algumas informações para criação do DER.

**Comment by Holyspear** [comment]
Aguardando documentação de requisitos para modelagem do banco.

**Comment by rhawan** [comment]
Conforme arquitetura proposta do projeto, não será necessário modelar esta camada de persistência, será utilizado o banco embarcado H2 no Spring Boot, portanto as entidades se criarão automaticamente.

Fechar esta issue

**Comment by Holyspear** [comment]
Finalizando Issue conforme mudança de banco no projeto.
