### ISSUE TITLE
Desenvolvimento da camada de MODELOS

### ISSUE THREAD

**Issue by Holyspear** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#4]
Desenvolver a camada de modelos da aplicação. Criação de classes e artefatos que farão a manipulação e intermediação das informações contidas entre a aplicação e o banco de dados. Essa atividade deve seguir os seguintes passos:
1 - Criar todos os artefatos presentes no banco de dados segundo modelagem DER;
2 - Gerar os relacionamentos necessários entre estes artefatos (Se for o caso), obedecendo modelagem padrão de relacionamentos do HIBERNATE;
3 - Testar e configurar a integração entre os artefatos através de classes de testes unitários ou validações de criação dos objetos;
4 - Testar a persistência dos artefatos através de classes de testes de criação dos objetos.

**Comment by d4nielfilho** [comment]
Conforme conversado, foi escolhido a utilização do Spring Boot, então não é preciso realizar esses precedimentos.
