### ISSUE TITLE
Desenvolvimento da camada de CONTROLE

### ISSUE THREAD

**Issue by Holyspear** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#5]
Desenvolver pacote com artefatos que controlam a aplicação em nível de conexão e controle do banco de dados, persistências e criação e manutenção das entidades contidas na aplicação.
Para esta atividade, necessário seguir os seguintes passos:
1 - Definir arquitetura de organização do pacote de CONTROLERS (JSF, PRIMEFACES, Etc.);
2 - obedecer os padrões estabelecidos para criação da camada de controle, tais como criação de novos objetos via INJECTIONS do JSF ou estrutura de CDI;
3 - Desenvolver artefatos de acordo com padrões pré-estabelecidos de comunicação com a camada View (Dependência da atividade das Views).

Esta atividade é dependente exclusivamente das atividades de CAMADA DE VIEWS E MODELOS.

**Comment by rhawan** [comment]
Implementação da camada de controle finalizada
