### ISSUE TITLE
Geração da RELEASE do projeto

### ISSUE THREAD

**Issue by rhawan** [FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano#9]
Ao término da iteração do projeto, gerar a release versão 1.0 no github. Orientações através do link: https://help.github.com/articles/creating-releases/

**Comment by Holyspear** [comment]
Release criada com sucesso.
Nome da Release: CadastroCliente
Release: v1.0
A mesma pode ser visualizada em :
https://github.com/FaculdadeAlfa/grupo-rhawan-irani-daniel-adriano/releases/tag/v1.0
